services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: quickchat
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    command: >
      sh -c "python src/manage.py migrate &&
             python src/manage.py collectstatic --noinput &&
             python src/manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://adminuser:password@db:5432/quickchat
      SECRET_KEY: django-insecure-micl#((a8wr**$_12b#a)si*8-eg#3#xxavta8o9%nmvlmm7lu
      CENTRIFUGO_API_KEY: jPhNbyCG_jlLRB73nR9pR5Qt_YuIicDo9cOJzBxAXIOUYxCbuwPZB8Ce1GDKopUzz8nHMA_C53ZgeFnFFCdkRA
    depends_on:
      - db
      - centrifugo
    networks:
      - app-network
    ports:
      - "8000:8000"

  centrifugo:
    image: centrifugo/centrifugo:v6.4.0
    volumes:
      - ./config.json:/centrifugo/config.json
    command: centrifugo -c /centrifugo/config.json
    networks:
      - app-network
    ports:
      - "8001:8001"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge